# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nspec.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x19\n\nDelRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1e\n\x0b\x44\x65lResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\"\x1c\n\x0cKeysResponse\x12\x0c\n\x04keys\x18\x01 \x03(\t2\xf1\x01\n\rLokiDBService\x12\"\n\x03\x44\x65l\x12\x0b.DelRequest\x1a\x0c.DelResponse\"\x00\x12\x39\n\x05\x46lush\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\"\n\x03Get\x12\x0b.GetRequest\x1a\x0c.GetResponse\"\x00\x12/\n\x04Keys\x12\x16.google.protobuf.Empty\x1a\r.KeysResponse\"\x00\x12,\n\x03Set\x12\x0b.SetRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_GETREQUEST = DESCRIPTOR.message_types_by_name['GetRequest']
_GETRESPONSE = DESCRIPTOR.message_types_by_name['GetResponse']
_SETREQUEST = DESCRIPTOR.message_types_by_name['SetRequest']
_DELREQUEST = DESCRIPTOR.message_types_by_name['DelRequest']
_DELRESPONSE = DESCRIPTOR.message_types_by_name['DelResponse']
_KEYSRESPONSE = DESCRIPTOR.message_types_by_name['KeysResponse']
GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'spec_pb2'
  # @@protoc_insertion_point(class_scope:GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRESPONSE,
  '__module__' : 'spec_pb2'
  # @@protoc_insertion_point(class_scope:GetResponse)
  })
_sym_db.RegisterMessage(GetResponse)

SetRequest = _reflection.GeneratedProtocolMessageType('SetRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETREQUEST,
  '__module__' : 'spec_pb2'
  # @@protoc_insertion_point(class_scope:SetRequest)
  })
_sym_db.RegisterMessage(SetRequest)

DelRequest = _reflection.GeneratedProtocolMessageType('DelRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELREQUEST,
  '__module__' : 'spec_pb2'
  # @@protoc_insertion_point(class_scope:DelRequest)
  })
_sym_db.RegisterMessage(DelRequest)

DelResponse = _reflection.GeneratedProtocolMessageType('DelResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELRESPONSE,
  '__module__' : 'spec_pb2'
  # @@protoc_insertion_point(class_scope:DelResponse)
  })
_sym_db.RegisterMessage(DelResponse)

KeysResponse = _reflection.GeneratedProtocolMessageType('KeysResponse', (_message.Message,), {
  'DESCRIPTOR' : _KEYSRESPONSE,
  '__module__' : 'spec_pb2'
  # @@protoc_insertion_point(class_scope:KeysResponse)
  })
_sym_db.RegisterMessage(KeysResponse)

_LOKIDBSERVICE = DESCRIPTOR.services_by_name['LokiDBService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETREQUEST._serialized_start=43
  _GETREQUEST._serialized_end=68
  _GETRESPONSE._serialized_start=70
  _GETRESPONSE._serialized_end=98
  _SETREQUEST._serialized_start=100
  _SETREQUEST._serialized_end=140
  _DELREQUEST._serialized_start=142
  _DELREQUEST._serialized_end=167
  _DELRESPONSE._serialized_start=169
  _DELRESPONSE._serialized_end=199
  _KEYSRESPONSE._serialized_start=201
  _KEYSRESPONSE._serialized_end=229
  _LOKIDBSERVICE._serialized_start=232
  _LOKIDBSERVICE._serialized_end=473
# @@protoc_insertion_point(module_scope)
